---
title: "Training Statistics"
author: "Samir Rehmtulla"
date: "February 26, 2018"
output: 
  html_document:
    self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr)
library(jsonlite)
library(lubridate)
library(plotly)
library(stringr)
library(plyr)
library(leaflet)
library(sp)
library(data.table)
library(googleway)
rm(list=ls())
options(stringsAsFactors = FALSE)
RActivites <- fromJSON(rawToChar(GET(url = "https://www.strava.com/api/v3/athlete/activities?after=1519601753&per_page=80&access_token=738ba7d3a2a53c870f699ae5a297383eef11f537")$content))
RActivites$start_date_local <- strtrim(RActivites$start_date_local, 10)

steadyRuns <- grep("steady", RActivites$name, ignore.case = TRUE)
restRuns <- grep("rest", RActivites$name, ignore.case = TRUE)
workRuns <- grep("work", RActivites$name, ignore.case = TRUE)
tempoRuns <- grep("tempo", RActivites$name, ignore.case = TRUE)
trackRuns <- grep("track", RActivites$name, ignore.case = TRUE)
longRuns <- grep("Long", RActivites$name, ignore.case = TRUE)
intenseRuns <- grep("intense", RActivites$name, ignore.case = TRUE)
WarmupRuns <- grep("warm", RActivites$name, ignore.case = TRUE)
CooldownRuns <- grep("cool", RActivites$name, ignore.case = TRUE)

ids <- RActivites$id
urlP1 <- rep("https://www.strava.com/api/v3/activities/", length(ids))
urlP2 <- rep("?access_token=738ba7d3a2a53c870f699ae5a297383eef11f537", length(ids))
PolylineURLs <- paste(urlP1, ids, urlP2, sep="")
Polylines <- c()
for(i in 1:length(PolylineURLs)) {
  Activity <- fromJSON(rawToChar(GET(url = PolylineURLs[[i]])$content))$map
  if(is.null(Activity$polyline))
  { Polylines[[i]] <- "" } else { Polylines[[i]] <- Activity$polyline}
}

RunType <- vector(mode = "character", length = nrow(RActivites))
for(i in 1:length(RunType)) {
  if(i %in% steadyRuns) { RunType[[i]] <- "Steady"}
  else if(i %in% intenseRuns) { RunType[[i]] <- "Intense" }
  else if(i %in% tempoRuns) { RunType[[i]] <- "Tempo" }
  else if(i %in% trackRuns) { RunType[[i]] <- "Track" }
  else if (i %in% longRuns) { RunType[[i]] <- "Long"}
  else if(i %in% workRuns) { RunType[[i]] <- 'Work' }
  else if(i %in% restRuns) { RunType[[i]] <- "Rest" }
  else if(i %in% WarmupRuns) { RunType[[i]] <- "Warm-up"}
  else if(i %in% CooldownRuns) { RunType[[i]] <- "Cool-down"}
  else { RunType[[i]] <- "Misc"}
}

Pace <- RActivites$moving_time/RActivites$distance/60*1000
Pace <- paste("<b>", floor(Pace), ":", str_pad(round((Pace - floor(Pace))*60), 2, pad = "0"), "/km", "</b>", sep = "")

RunningData <- data.frame(RActivites$start_date_local, RActivites$distance/1000.0, RActivites$moving_time, RunType, Pace, Polylines)
RunningData <- rename(RunningData, c("RActivites.start_date_local" = "Date", "RActivites.distance.1000" = "Distance", "RActivites.moving_time" = "Time"))
```

## Training Plan for Sub-19 Minute 5K

Special Thanks to Tanner Geary, UBC Thunderbirds Track And Field, for putting together the training plan!

```{r Week1, echo = FALSE, warning = FALSE}
trainingWeeks <- htmltools::tagList()
dates <- seq(as.Date("2018/2/26"), Sys.Date(), by = "day")

p <- plot_ly(width = 850, height = 500, type = "bar", hoverinfo = "all") %>%
  
  add_trace(x = dates, y = integer(length(dates)), showlegend = F) %>%
  
  add_trace(x = RunningData[RunningData$RunType == "Work",]$Date, y = RunningData[RunningData$RunType == "Work",]$Distance, text = RunningData[RunningData$RunType == "Work",]$Pace, textposition = 'auto',  marker = list(line = list(color = 'rgb(8,48,107)', width = 2), color = 'rgba(160,70, 255,0.6)'), name = "Run to or from work") %>%
  
    add_trace(x = RunningData[RunningData$RunType=="Warm-up",]$Date,y=RunningData[RunningData$RunType == "Warm-up",]$Distance, text = RunningData[RunningData$RunType == "Warm-up",]$Pace, textposition = 'auto', marker = list(color = 'rgba(100,255,100,0.6)', line = list(color = 'rgb(8,48,107)', width = 2)), name = "Warm-up Run") %>%
  
  add_trace(x = RunningData[RunningData$RunType == "Steady",]$Date, y=RunningData[RunningData$RunType == "Steady",]$Distance, text = RunningData[RunningData$RunType == "Steady",]$Pace, textposition = 'auto', marker = list(color = 'rgba(255, 100, 100, 0.6)', line = list(color = 'rgb(8,48,107)', width = 2)), name = "Steady-State Run") %>%
  
  add_trace(x = RunningData[RunningData$RunType == "Rest",]$Date, y = RunningData[RunningData$RunType == "Rest",]$Distance, text = RunningData[RunningData$RunType == "Rest",]$Pace, textposition = 'auto', marker = list(color = 'rgba(255, 255, 100, 0.6)', line = list(color = 'rgb(8,48,107)', width = 2)), name = "Recovery Run") %>%
  
  add_trace(x = RunningData[RunningData$RunType == "Track",]$Date, y = RunningData[RunningData$RunType == "Track",]$Distance, text = RunningData[RunningData$RunType == "Track",]$Pace, textposition = 'auto', marker = list(color = 'rgba(255, 100, 255, 0.6)', line = list(color = 'rgb(8,48,107)', width = 2)), name = "Track Intervals") %>%
  
  add_trace(x = RunningData[RunningData$RunType == "Long",]$Date, y = RunningData[RunningData$RunType == "Long",]$Distance, text = RunningData[RunningData$RunType == "Long",]$Pace, textposition = 'auto', marker = list(color = 'rgba(50, 150, 255, 0.6)', line = list(color = 'rgb(8,48,107)', width = 2)), name = "Long Run") %>%
  
  add_trace(x = RunningData[RunningData$RunType == "Cool-down",]$Date, y = RunningData[RunningData$RunType == "Cool-down",]$Distance, text = RunningData[RunningData$RunType == "Cool-down",]$Pace, textposition = 'auto', marker = list(color = 'rgba(100, 255, 255, 0.6)', line = list(color = 'rgb(8,48,107)', width = 2)), name = "Cool-down") %>%
  
  layout(barmode = "stack",  title = paste("Training Plan Week 1 -", signif(sum(RunningData$Distance), 4), "km"), xaxis = list(title = "Date"), yaxis = list(title = "Distance (km)"))
p

map_key <- 'AIzaSyC2_ZQpyvUMYMm2FZh3HouwqavsnF8QRG4'
x <- google_map(key = map_key, data = RunningData) %>%
  add_polylines(polyline = "Polylines", stroke_colour = "#00FFFF")
x
```
